/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/devtools-panel/': RouteRecordInfo<'/devtools-panel/', '/devtools-panel', Record<never, never>, Record<never, never>>,
    '/options-page/': RouteRecordInfo<'/options-page/', '/options-page', Record<never, never>, Record<never, never>>,
    '/options-page/about': RouteRecordInfo<'/options-page/about', '/options-page/about', Record<never, never>, Record<never, never>>,
    '/options-page/dataEditor': RouteRecordInfo<'/options-page/dataEditor', '/options-page/dataEditor', Record<never, never>, Record<never, never>>,
    '/options-page/domainEditor': RouteRecordInfo<'/options-page/domainEditor', '/options-page/domainEditor', Record<never, never>, Record<never, never>>,
    '/options-page/domainList': RouteRecordInfo<'/options-page/domainList', '/options-page/domainList', Record<never, never>, Record<never, never>>,
    '/options-page/uaEditor': RouteRecordInfo<'/options-page/uaEditor', '/options-page/uaEditor', Record<never, never>, Record<never, never>>,
  }
}
